image: ubuntu:latest

stages:
  - build
  - deploy
  - announce

before_script:
  - export TERM=xterm
  - mkdir -p public/ pdfs/

pdf:
  stage: build
  image: clovisai/latex:latest
  script:
    - make pdf
    - mv semestre-*/*.pdf pdfs/
    - for dir in semestre-*; do mkdir -p pdfs/$dir; cp $dir/*.pdf pdfs/$dir/; done
  artifacts:
    paths:
      - pdfs

pages:
  stage: deploy
  script:
    - ./html/build-site.sh
  dependencies:
    - pdf
  artifacts:
    paths:
      - public
  only:
    - master

telegram:
  stage: announce
  image: clovisai/wget:latest
  script:
    - wget "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage?parse_mode=markdown&chat_id=${CHAT_ID}&text=Les%20cours%20ont%20%C3%A9t%C3%A9%20mis%20%C3%A0%20jour%20%0A%0A[Voir%20la%20liste%20des%20fichiers](https://clovis-ai.gitlab.io/enseirb-info/)"
  only:
    - master
